services:
  - type: web
    name: spontaneous-meetup-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        value: "mongodb+srv://diablosnachos99:ZBjNved2BR2xvYmi@cluster0.3lvis.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
        sync: false
      - key: JWT_SECRET
        value: "3a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z"
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        value: "https://touched-airedale-15214.upstash.io"
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        value: "ATtuAAIjcDEwYzg1ZmQ5MDM4N2Y0N2NjODJkYzE0OTcwOTU3Yzc0NnAxMA"
        sync: false
